version: '3'
services:
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./site/index.html:/var/www/site1/index.html"
      - "./site/index1.html:/var/www/site2/index.html"
      - "./frontend/dist:/var/www/public"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongo:/data/db
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
